blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/hyochan/react-native-iap/discussions
    about: Please ask and answer questions here. Discussions are like a combination of Stack Overflow and Reddit, great for getting help, sharing ideas, and general conversations.
